---

dependencies: []

galaxy_info:
  author: veaglem@gmail.com
  description:
  license: GPLv3
  min_ansible_version: 2.9.17
  platforms:
  - name: Ubuntu
    versions:
    - 20.04
  categories:
    - system
    - monitoring
